// <auto-generated />
namespace Dare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gotgoogleAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gotgoogleAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161846188_got google API"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
